name: Nix Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install Nix
      uses: cachix/install-nix-action@v24
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          
    - name: Setup Nix cache
      uses: cachix/cachix-action@v12
      if: ${{ secrets.CACHIX_AUTH_TOKEN != '' }}
      with:
        name: nix-community
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        skipPush: true
        
    - name: Update flake inputs
      run: nix flake update
      
    - name: Check flake
      run: nix flake check
      
    - name: Build package
      run: nix build .#virtualkeyboard-adapter
      
    - name: Build default package
      run: nix build
      
    - name: Show build results
      run: ls -la result*